

POST http://localhost:8080/check-in-customer
Content-Type: application/json

{
   	"FullName":    "A",
	"PhoneNumber": "xxxx",
	"Type":        "Priority"
}

###
POST http://localhost:8080/check-in-customer
Content-Type: application/json

{
   	"FullName":    "B",
	"PhoneNumber": "xxxx",
	"Type":        "Priority"
}


###
POST http://localhost:8080/check-in-customer
Content-Type: application/json

{
   	"FullName":    "C",
	"PhoneNumber": "xxxxx",
	"Type":        "Priority"
}

###
POST http://localhost:8080/check-in-customer
Content-Type: application/json

{
   	"FullName":    "D",
	"PhoneNumber": "xxxxx",
	"Type":        "Priority"
}

###
POST http://localhost:8080/check-in-customer
Content-Type: application/json

{
   	"FullName":    "E",
	"PhoneNumber": "xxxxx",
	"Type":        "Standard"
}

###
POST http://localhost:8080/check-in-customer
Content-Type: application/json

{
   	"FullName":    "F",
	"PhoneNumber": "xxxxx",
	"Type":        "Standard"
}


###
GET http://localhost:8080/get-all-vip-customers

###
GET http://localhost:8080/get-all-standard-customers

###
GET http://localhost:8080/get-next-customer-schedulerB


###
GET http://localhost:8080/get-next-customer-schedulerB


###
GET http://localhost:8080/get-next-customer-schedulerB


###
GET http://localhost:8080/get-next-customer-schedulerB

###
GET http://localhost:8080/get-next-customer-schedulerB

###
GET http://localhost:8080/get-next-customer-schedulerB




